### ISSUE TITLE
Length of compressed solution is not decreased

### ISSUE THREAD

**Issue by nulaft** [efrantar/rob-twophase#11] opened 2020-08-27 13:31 UTC
https://github.com/efrantar/rob-twophase/blob/70db5f9a065e4d1c47a41b57fb86eb78a7847923/src/main.cpp#L250-L259

The solutions are ordered using the uncompressed length, and the uncompressed length is shown after the (compressed) move string. This seems to be intentional, judging from the comment. However, for me the expected output of the solver should be the shortest solution found (or the -n shortest solutions, in ascending ordering).

This could be achieved by compressing a discovered solution before it is added to the sols priority queue of solutions in the function report_sol:
https://github.com/efrantar/rob-twophase/blob/70db5f9a065e4d1c47a41b57fb86eb78a7847923/src/solve.cpp#L280-L287

**Comment by efrantar** [comment] 2020-08-27 18:31
The main purpose of compression is to turn QT solutions into HT as this is actually quite annoying to do outside of this program for AXQT but you probably want to execute `(U2 D)` instead of `U (U D)` on a robot. However, when you are searching in QT you are interested in how short a solution is in QT (and not after conversion to HT or you would be directly searching there), hence I think sorting by their actual uncompressed length makes sense.

You are probably using compression to handle the problem described in issue #8. Best see my answer for a workaround there.

**Comment by efrantar** [comment] 2020-08-28 09:58
As printing the uncompressed length is indeed the intended behavior as outlined above and since #8 is now fixed with 23f3098d0f45949bd1b68959fdc16e0d2317f8b5, I will close this too.

**Closed as completed by efrantar** 2020-08-28 09:58 UTC
